Rails.application.routes.draw do
  get '/new_organization/:id', to: 'organizations#new', as: 'new_organization'
  post '/create_organization/:user_id', to: 'organizations#create', as: 'create_organization'
  get '/organization/:id', to: 'organizations#show', as: 'organization'
  delete '/delete_organization/:id', to: 'organizations#destroy', as: 'delete_organization'
  get 'clear_business' => 'common_actions#clear_business'
  get 'find_business' => 'common_actions#find_business'
  get 'documents' => 'common_actions#documents'
  get 'declarations' => 'common_actions#declarations'
  get '/new_vehicle/:id', to: 'vehicles#new', as: 'new_vehicle'
  post '/create_vehicle/:user_id', to: 'vehicles#create'
  get '/vehicle/:id', to: 'vehicles#show', as: 'vehicle'
  delete '/delete_vehicle/:id', to: 'vehicles#destroy', as: 'delete_vehicle'
  get '/new_service_vehicle/:id', to: 'service_vehicles#new', as: 'new_service_vehicle'
  post '/create_service_vehicle/:organization_id', to: 'service_vehicles#create'
  get '/service_vehicle/:id', to: 'service_vehicles#show', as: 'service_vehicle'
  delete '/delete_service_vehicle/:id', to: 'service_vehicles#destroy', as: 'delete_service_vehicle'
  get '/new_estate/:id', to: 'estates#new', as: 'new_estate'
  post '/create_estate/:user_id', to: 'estates#create', as: 'create_estate'
  get '/estate/:id', to: 'estates#show', as: 'estate'
  delete '/delete_estate/:id', to: 'estates#destroy', as: 'delete_estate'
  get '/new_service_estate/:id', to: 'service_estates#new', as: 'new_service_estate'
  post '/create_service_estate/:organization_id', to: 'service_estates#create', as: 'create_service_estate'
  get '/service_estate/:id', to: 'service_estates#show', as: 'service_estate'
  delete '/delete_service_estate/:id', to: 'service_estates#destroy', as: 'delete_service_estate'
  get 'index' => 'inspector_actions#index'
  get 'users_list' => 'inspector_actions#users_list'
  get 'estates_list' => 'inspector_actions#estates_list'
  get 'vehicles_list' => 'inspector_actions#vehicles_list'
  get 'organizations_list' => 'inspector_actions#organizations_list'
  get '/show_user/:id', to: 'inspector_actions#show_user', as: 'show_user'
  get '/edit_user/:id', to: 'inspector_actions#edit_user', as: 'edit_user'
  patch '/update_user/:id', to: 'inspector_actions#update_user', as: 'update_user'
  root 'main_page#home'
  get 'sessions/new'
  get 'account' => 'personal_actions#account'
  get 'become_entrepreneur' => 'personal_actions#become_entrepreneur'
  patch 'confirm_status' => 'personal_actions#confirm_status'
  get 'signup' => 'users#new'
  get 'show' => 'users#show'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  patch 'update' => 'users#update'

  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end
